import type { Collection } from "./types.js";

export const ukCounties: Collection = {
  id: "uk-counties",
  name: "UK Historic Counties",
  description: "Flags of the historic counties of England.",
  groupLabel: "Region",
  itemLabel: "county",
  groups: [
    { id: "south-west",               name: "South West" },
    { id: "south-east",               name: "South East" },
    { id: "london",                   name: "London" },
    { id: "east-of-england",          name: "East of England" },
    { id: "east-midlands",            name: "East Midlands" },
    { id: "west-midlands",            name: "West Midlands" },
    { id: "yorkshire-and-the-humber", name: "Yorkshire and the Humber" },
    { id: "north-west",               name: "North West" },
    { id: "north-east",               name: "North East" },
  ],
  flags: [
    { code: "bdf", name: "Bedfordshire",     group: "east-of-england",          colors: ["red","blue","black","white","yellow"], patterns: [], symbols: [], ext: "svg" },
    { code: "bkm", name: "Buckinghamshire",  group: "south-east",               colors: ["red","yellow","orange","white"],       patterns: [], symbols: ["swan"], ext: "svg" },
    { code: "brk", name: "Berkshire",        group: "south-east",               colors: ["green","red","yellow","white","black"],patterns: [], symbols: ["stag"], ext: "svg" },
    { code: "cam", name: "Cambridgeshire",   group: "east-of-england",          colors: ["green","yellow","blue"],                patterns: [], symbols: [], ext: "svg" },
    { code: "chs", name: "Cheshire",         group: "north-west",               colors: ["red","blue","yellow"],                  patterns: ["bicolor-horizontal"], symbols: ["sheaf"], ext: "svg" },
    { code: "con", name: "Cornwall",         group: "south-west",               colors: ["white","black"],                        patterns: ["cross"], symbols: [], ext: "svg" },
    { code: "cul", name: "Cumberland",       group: "north-west",               colors: ["white","blue","green"],                 patterns: [], symbols: [], ext: "svg" },
    { code: "dby", name: "Derbyshire",       group: "east-midlands",            colors: ["green","yellow","white","blue"],        patterns: ["cross"], symbols: ["rose","tudor-rose"], ext: "svg" },
    { code: "dev", name: "Devon",            group: "south-west",               colors: ["green","black","white"],                patterns: ["cross"], symbols: [], ext: "svg" },
    { code: "dor", name: "Dorset",           group: "south-west",               colors: ["yellow","white","red"],                 patterns: ["cross"], symbols: [], ext: "svg" },
    { code: "dur", name: "County Durham",    group: "north-east",               colors: ["blue","yellow"],                        patterns: ["cross"], symbols: [], ext: "svg" },
    { code: "ess", name: "Essex",            group: "east-of-england",          colors: ["red","white","yellow"],                 patterns: [], symbols: ["seax"], ext: "svg" },
    { code: "gls", name: "Gloucestershire",  group: "south-west",               colors: ["blue","green"],                         patterns: ["stripes-horizontal"], symbols: ["sword"], ext: "svg" },
    { code: "ham", name: "Hampshire",        group: "south-east",               colors: ["red","white","yellow","green"],         patterns: [], symbols: ["rose","crown"], ext: "svg" },
    { code: "hef", name: "Herefordshire",    group: "west-midlands",            colors: ["white","red","blue","black"],           patterns: [], symbols: ["lion"], ext: "svg" },
    { code: "hrt", name: "Hertfordshire",    group: "east-of-england",          colors: ["red","blue","yellow","white","black"],  patterns: [], symbols: ["stag"], ext: "svg" },
    { code: "hun", name: "Huntingdonshire",  group: "east-of-england",          colors: ["green","yellow","white","black"],       patterns: [], symbols: ["hunting-horn"], ext: "svg" },
    { code: "ken", name: "Kent",             group: "south-east",               colors: ["red","white"],                          patterns: [], symbols: ["horse"], ext: "svg" },
    { code: "lan", name: "Lancashire",       group: "north-west",               colors: ["red","yellow"],                         patterns: [], symbols: ["rose"], ext: "svg" },
    { code: "lei", name: "Leicestershire",   group: "east-midlands",            colors: ["white","red"],                          patterns: ["cross"], symbols: ["cinquefoil"], ext: "svg" },
    { code: "lin", name: "Lincolnshire",     group: "east-midlands",            colors: ["green","blue","yellow","red"],          patterns: ["cross"], symbols: ["fleur-de-lis"], ext: "svg" },
    { code: "mdx", name: "Middlesex",        group: "london",                   colors: ["red","yellow","white"],                 patterns: [], symbols: ["seaxes","crown"], ext: "svg" },
    { code: "nbl", name: "Northumberland",   group: "north-east",               colors: ["yellow","red"],                         patterns: ["stripes-vertical"], symbols: [], ext: "svg" },
    { code: "nfk", name: "Norfolk",          group: "east-of-england",          colors: ["yellow","white"],                       patterns: [], symbols: ["cross"], ext: "svg" },
    { code: "nth", name: "Northamptonshire", group: "east-midlands",            colors: ["green","red","orange"],                 patterns: ["cross"], symbols: ["tudor-rose"], ext: "svg" },
    { code: "ntt", name: "Nottinghamshire",  group: "east-midlands",            colors: ["red","white"],                          patterns: ["cross"], symbols: ["crown"], ext: "svg" },
    { code: "oxf", name: "Oxfordshire",      group: "south-east",               colors: ["yellow","red","green","white"],         patterns: [], symbols: ["ox"], ext: "svg" },
    { code: "rut", name: "Rutland",          group: "east-midlands",            colors: ["yellow","red","green"],                 patterns: [], symbols: ["acorn","horseshoe"], ext: "svg" },
    { code: "sal", name: "Shropshire",       group: "west-midlands",            colors: ["yellow","blue"],                        patterns: [], symbols: ["leopards"], ext: "svg" },
    { code: "sfk", name: "Suffolk",          group: "east-of-england",          colors: ["yellow","red","blue"],                  patterns: [], symbols: ["crown","arrows"], ext: "svg" },
    { code: "som", name: "Somerset",         group: "south-west",               colors: ["red","yellow","black","blue"],          patterns: [], symbols: ["dragon"], ext: "svg" },
    { code: "sry", name: "Surrey",           group: "south-east",               colors: ["yellow","blue"],                        patterns: ["checkered"], symbols: [], ext: "svg" },
    { code: "ssx", name: "Sussex",           group: "south-east",               colors: ["blue","yellow"],                        patterns: [], symbols: ["martlets"], ext: "svg" },
    { code: "sts", name: "Staffordshire",    group: "west-midlands",            colors: ["yellow","red"],                         patterns: ["chevron"], symbols: ["stafford-knot"], ext: "svg" },
    { code: "war", name: "Warwickshire",     group: "west-midlands",            colors: ["white","red"],                          patterns: ["cross"], symbols: ["bear"], ext: "svg" },
    { code: "wes", name: "Westmorland",      group: "north-west",               colors: ["red","yellow","white"],                 patterns: [], symbols: ["apples"], ext: "svg" },
    { code: "wil", name: "Wiltshire",        group: "south-west",               colors: ["green","red","white"],                  patterns: [], symbols: ["bustard"], ext: "svg" },
    { code: "wor", name: "Worcestershire",   group: "west-midlands",            colors: ["green","blue","white"],                 patterns: [], symbols: ["pear"], ext: "svg" },
    { code: "yks", name: "Yorkshire",        group: "yorkshire-and-the-humber", colors: ["white","blue"],                         patterns: [], symbols: ["white-rose"], ext: "svg" },
  ],
};
