import type { Collection } from "./types.js";

export const usStates: Collection = {
  id: "us-states",
  name: "US State Flags",
  description: "Flags of the 50 United States and the District of Columbia.",
  groupLabel: "Region",
  itemLabel: "state",
  groups: [
    { id: "northeast", name: "Northeast" },
    { id: "midwest",   name: "Midwest" },
    { id: "south",     name: "South" },
    { id: "west",      name: "West" },
  ],
  flags: [
    { code: "ak", name: "Alaska",               group: "west",      colors: ["blue","yellow"],                  patterns: [], symbols: ["stars"], ext: "svg" },
    { code: "al", name: "Alabama",              group: "south",     colors: ["red","white"],                    patterns: ["x-cross"], symbols: [], ext: "svg" },
    { code: "ar", name: "Arkansas",             group: "south",     colors: ["red","white","blue"],             patterns: [], symbols: ["stars"], ext: "svg" },
    { code: "az", name: "Arizona",              group: "west",      colors: ["red","yellow","blue"],            patterns: ["stripes-rays"], symbols: ["star","sun"], ext: "svg" },
    { code: "ca", name: "California",           group: "west",      colors: ["white","red","green"],            patterns: ["stripes-horizontal"], symbols: ["bear","star"], ext: "svg" },
    { code: "co", name: "Colorado",             group: "west",      colors: ["red","white","blue","yellow"],    patterns: ["stripes-horizontal"], symbols: ["letter"], ext: "svg" },
    { code: "ct", name: "Connecticut",          group: "northeast", colors: ["blue","white"],                   patterns: [], symbols: ["shield","vines"], ext: "svg" },
    { code: "dc", name: "District of Columbia", group: "south",     colors: ["red","white"],                    patterns: ["stripes-horizontal"], symbols: ["stars"], ext: "svg" },
    { code: "de", name: "Delaware",             group: "south",     colors: ["blue","yellow"],                  patterns: ["diamond"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "fl", name: "Florida",              group: "south",     colors: ["white","red"],                    patterns: ["x-cross"], symbols: ["seal"], ext: "svg" },
    { code: "ga", name: "Georgia",              group: "south",     colors: ["red","white","blue"],             patterns: ["stripes-horizontal"], symbols: ["seal","stars"], ext: "svg" },
    { code: "hi", name: "Hawaii",               group: "west",      colors: ["red","white","blue"],             patterns: ["stripes-horizontal","canton"], symbols: ["union-jack"], ext: "svg" },
    { code: "ia", name: "Iowa",                 group: "midwest",   colors: ["blue","white","red"],             patterns: ["tricolor-vertical"], symbols: ["eagle"], ext: "svg" },
    { code: "id", name: "Idaho",                group: "west",      colors: ["blue","red","yellow"],            patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "il", name: "Illinois",             group: "midwest",   colors: ["white","red","blue"],             patterns: [], symbols: ["eagle","seal"], ext: "svg" },
    { code: "in", name: "Indiana",              group: "midwest",   colors: ["blue","yellow"],                  patterns: [], symbols: ["torch","stars"], ext: "svg" },
    { code: "ks", name: "Kansas",               group: "midwest",   colors: ["blue","yellow"],                  patterns: [], symbols: ["seal","sunflower"], ext: "svg" },
    { code: "ky", name: "Kentucky",             group: "south",     colors: ["blue","yellow"],                  patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "la", name: "Louisiana",            group: "south",     colors: ["blue","white","yellow"],          patterns: [], symbols: ["pelican"], ext: "svg" },
    { code: "ma", name: "Massachusetts",        group: "northeast", colors: ["white","blue"],                   patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "md", name: "Maryland",             group: "south",     colors: ["red","white","yellow","black"],   patterns: ["quarters"], symbols: ["heraldic"], ext: "svg" },
    { code: "me", name: "Maine",                group: "northeast", colors: ["blue","white"],                   patterns: [], symbols: ["seal","pine"], ext: "svg" },
    { code: "mi", name: "Michigan",             group: "midwest",   colors: ["blue","red","white"],             patterns: [], symbols: ["seal","eagle","elk","moose"], ext: "svg" },
    { code: "mn", name: "Minnesota",            group: "midwest",   colors: ["blue","white"],                   patterns: [], symbols: ["star"], ext: "svg" },
    { code: "mo", name: "Missouri",             group: "midwest",   colors: ["red","white","blue"],             patterns: ["tricolor-horizontal"], symbols: ["seal","stars"], ext: "svg" },
    { code: "ms", name: "Mississippi",          group: "south",     colors: ["red","white","blue"],             patterns: ["stripes-horizontal"], symbols: ["magnolia"], ext: "svg" },
    { code: "mt", name: "Montana",              group: "west",      colors: ["blue","green"],                   patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "nc", name: "North Carolina",       group: "south",     colors: ["red","white","blue"],             patterns: ["stripes-horizontal","canton"], symbols: ["star"], ext: "svg" },
    { code: "nd", name: "North Dakota",         group: "midwest",   colors: ["blue","red","white"],             patterns: [], symbols: ["eagle"], ext: "svg" },
    { code: "ne", name: "Nebraska",             group: "midwest",   colors: ["blue","yellow"],                  patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "nh", name: "New Hampshire",        group: "northeast", colors: ["blue","white"],                   patterns: [], symbols: ["seal","ship"], ext: "svg" },
    { code: "nj", name: "New Jersey",           group: "northeast", colors: ["yellow","blue"],                  patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "nm", name: "New Mexico",           group: "west",      colors: ["red","yellow"],                   patterns: [], symbols: ["zia-sun"], ext: "svg" },
    { code: "nv", name: "Nevada",               group: "west",      colors: ["blue","white","yellow"],          patterns: ["canton"], symbols: ["star","wreath"], ext: "svg" },
    { code: "ny", name: "New York",             group: "northeast", colors: ["blue","white"],                   patterns: [], symbols: ["seal","eagle"], ext: "svg" },
    { code: "oh", name: "Ohio",                 group: "midwest",   colors: ["red","white","blue"],             patterns: ["swallowtail"], symbols: ["stars","circle"], ext: "svg" },
    { code: "ok", name: "Oklahoma",             group: "south",     colors: ["blue","white","red"],             patterns: [], symbols: ["shield","pipe"], ext: "svg" },
    { code: "or", name: "Oregon",               group: "west",      colors: ["blue","yellow"],                  patterns: [], symbols: ["seal","beaver"], ext: "svg" },
    { code: "pa", name: "Pennsylvania",         group: "northeast", colors: ["blue","yellow"],                  patterns: [], symbols: ["coat-of-arms","horses","eagle"], ext: "svg" },
    { code: "ri", name: "Rhode Island",         group: "northeast", colors: ["white","yellow","blue"],          patterns: [], symbols: ["anchor","stars"], ext: "svg" },
    { code: "sc", name: "South Carolina",       group: "south",     colors: ["blue","white"],                   patterns: [], symbols: ["palmetto","crescent"], ext: "svg" },
    { code: "sd", name: "South Dakota",         group: "midwest",   colors: ["blue","yellow"],                  patterns: [], symbols: ["seal","sun"], ext: "svg" },
    { code: "tn", name: "Tennessee",            group: "south",     colors: ["red","white","blue"],             patterns: ["stripes-vertical"], symbols: ["stars"], ext: "svg" },
    { code: "tx", name: "Texas",                group: "south",     colors: ["red","white","blue"],             patterns: ["stripes-horizontal","canton"], symbols: ["star"], ext: "svg" },
    { code: "ut", name: "Utah",                 group: "west",      colors: ["white","blue","red","yellow"],    patterns: ["chevron"], symbols: ["beehive","stars"], ext: "svg" },
    { code: "va", name: "Virginia",             group: "south",     colors: ["blue","white"],                   patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "vt", name: "Vermont",              group: "northeast", colors: ["blue","white"],                   patterns: [], symbols: ["coat-of-arms","pine","stag"], ext: "svg" },
    { code: "wa", name: "Washington",           group: "west",      colors: ["green","yellow"],                 patterns: [], symbols: ["seal"], ext: "svg" },
    { code: "wi", name: "Wisconsin",            group: "midwest",   colors: ["blue","yellow"],                  patterns: [], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "wv", name: "West Virginia",        group: "south",     colors: ["white","blue","red","yellow"],    patterns: [], symbols: ["seal","laurel"], ext: "svg" },
    { code: "wy", name: "Wyoming",              group: "west",      colors: ["red","white","blue"],             patterns: [], symbols: ["bison","seal"], ext: "svg" },
  ],
};
