import type { Collection } from "./types.js";

export const world: Collection = {
  id: "world",
  name: "World Flags",
  description: "Flags of sovereign nations across the globe.",
  groupLabel: "Continent",
  itemLabel: "country",
  groups: [
    { id: "europe",         name: "Europe" },
    { id: "africa",         name: "Africa" },
    { id: "asia",           name: "Asia" },
    { id: "north-america",  name: "North America" },
    { id: "south-america",  name: "South America" },
    { id: "oceania",        name: "Oceania" },
  ],
  flags: [
    { code: "ad", name: "Andorra", group: "europe", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "ae", name: "United Arab Emirates", group: "asia", colors: ["red","green","white","black"], patterns: ["stripes-horizontal","pan-arab"], symbols: [], ext: "svg" },
    { code: "af", name: "Afghanistan", group: "asia", colors: ["black","red","green"], patterns: ["tricolor-vertical"], symbols: ["emblem"], ext: "svg" },
    { code: "ag", name: "Antigua and Barbuda", group: "north-america", colors: ["red","black","blue","yellow"], patterns: ["triangle"], symbols: ["sun"], ext: "svg" },
    { code: "al", name: "Albania", group: "europe", colors: ["red","black"], patterns: [], symbols: ["eagle"], ext: "svg" },
    { code: "am", name: "Armenia", group: "asia", colors: ["red","blue","orange"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "ao", name: "Angola", group: "africa", colors: ["red","black","yellow"], patterns: ["bicolor-horizontal"], symbols: ["emblem","star"], ext: "svg" },
    { code: "ar", name: "Argentina", group: "south-america", colors: ["blue","white"], patterns: ["stripes-horizontal"], symbols: ["sun"], ext: "svg" },
    { code: "at", name: "Austria", group: "europe", colors: ["red","white"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "au", name: "Australia", group: "oceania", colors: ["blue","red","white"], patterns: ["canton"], symbols: ["union-jack","stars"], ext: "svg" },
    { code: "az", name: "Azerbaijan", group: "asia", colors: ["blue","red","green"], patterns: ["tricolor-horizontal"], symbols: ["crescent","star"], ext: "svg" },
    { code: "ba", name: "Bosnia and Herzegovina", group: "europe", colors: ["blue","yellow","white"], patterns: ["triangle"], symbols: ["stars"], ext: "svg" },
    { code: "bb", name: "Barbados", group: "north-america", colors: ["blue","yellow"], patterns: ["tricolor-vertical"], symbols: ["trident"], ext: "svg" },
    { code: "bd", name: "Bangladesh", group: "asia", colors: ["green","red"], patterns: ["circle"], symbols: [], ext: "svg" },
    { code: "be", name: "Belgium", group: "europe", colors: ["black","yellow","red"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "bf", name: "Burkina Faso", group: "africa", colors: ["red","green"], patterns: ["bicolor-horizontal","pan-african"], symbols: ["star"], ext: "svg" },
    { code: "bg", name: "Bulgaria", group: "europe", colors: ["white","green","red"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "bh", name: "Bahrain", group: "asia", colors: ["red","white"], patterns: ["chevron"], symbols: [], ext: "svg" },
    { code: "bi", name: "Burundi", group: "africa", colors: ["red","white","green"], patterns: ["diagonal","circle"], symbols: ["stars"], ext: "svg" },
    { code: "bj", name: "Benin", group: "africa", colors: ["green","yellow","red"], patterns: ["pan-african"], symbols: [], ext: "svg" },
    { code: "bn", name: "Brunei", group: "asia", colors: ["yellow","white","black"], patterns: ["diagonal"], symbols: ["emblem"], ext: "svg" },
    { code: "bo", name: "Bolivia", group: "south-america", colors: ["red","yellow","green"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "br", name: "Brazil", group: "south-america", colors: ["green","yellow","blue","white"], patterns: ["circle"], symbols: ["stars"], ext: "svg" },
    { code: "bs", name: "Bahamas", group: "north-america", colors: ["blue","yellow","black"], patterns: ["stripes-horizontal","triangle"], symbols: [], ext: "svg" },
    { code: "bt", name: "Bhutan", group: "asia", colors: ["orange","yellow"], patterns: ["diagonal"], symbols: ["dragon"], ext: "svg" },
    { code: "bw", name: "Botswana", group: "africa", colors: ["blue","white","black"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "by", name: "Belarus", group: "europe", colors: ["red","green","white"], patterns: [], symbols: ["pattern"], ext: "svg" },
    { code: "bz", name: "Belize", group: "north-america", colors: ["blue","red","white"], patterns: ["circle"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "ca", name: "Canada", group: "north-america", colors: ["red","white"], patterns: [], symbols: ["tree"], ext: "svg" },
    { code: "cd", name: "Democratic Republic of the Congo", group: "africa", colors: ["blue","red","yellow"], patterns: ["diagonal"], symbols: ["star"], ext: "svg" },
    { code: "cf", name: "Central African Republic", group: "africa", colors: ["blue","white","green","yellow","red"], patterns: ["stripes-horizontal"], symbols: ["star"], ext: "svg" },
    { code: "cg", name: "Republic of the Congo", group: "africa", colors: ["green","yellow","red"], patterns: ["diagonal"], symbols: [], ext: "svg" },
    { code: "ch", name: "Switzerland", group: "europe", colors: ["red","white"], patterns: ["cross"], symbols: [], ext: "svg" },
    { code: "ci", name: "Ivory Coast", group: "africa", colors: ["orange","white","green"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "cl", name: "Chile", group: "south-america", colors: ["red","white","blue"], patterns: ["canton"], symbols: ["star"], ext: "svg" },
    { code: "cm", name: "Cameroon", group: "africa", colors: ["green","red","yellow"], patterns: ["tricolor-vertical","pan-african"], symbols: ["star"], ext: "svg" },
    { code: "cn", name: "China", group: "asia", colors: ["red","yellow"], patterns: [], symbols: ["stars"], ext: "svg" },
    { code: "co", name: "Colombia", group: "south-america", colors: ["yellow","blue","red"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "cr", name: "Costa Rica", group: "north-america", colors: ["blue","white","red"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "cu", name: "Cuba", group: "north-america", colors: ["blue","white","red"], patterns: ["stripes-horizontal","triangle"], symbols: ["star"], ext: "svg" },
    { code: "cv", name: "Cape Verde", group: "africa", colors: ["blue","white","red"], patterns: ["stripes-horizontal","circle"], symbols: ["stars"], ext: "svg" },
    { code: "cy", name: "Cyprus", group: "europe", colors: ["white","orange"], patterns: [], symbols: ["emblem"], ext: "svg" },
    { code: "cz", name: "Czech Republic", group: "europe", colors: ["white","red","blue"], patterns: ["triangle"], symbols: [], ext: "svg" },
    { code: "de", name: "Germany", group: "europe", colors: ["black","red","yellow"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "dj", name: "Djibouti", group: "africa", colors: ["blue","green","white"], patterns: ["triangle"], symbols: ["star"], ext: "svg" },
    { code: "dk", name: "Denmark", group: "europe", colors: ["red","white"], patterns: ["nordic-cross"], symbols: [], ext: "svg" },
    { code: "dm", name: "Dominica", group: "north-america", colors: ["green","red","yellow","black","white"], patterns: ["cross","circle"], symbols: ["bird"], ext: "svg" },
    { code: "do", name: "Dominican Republic", group: "north-america", colors: ["red","blue","white"], patterns: ["cross"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "dz", name: "Algeria", group: "africa", colors: ["green","white","red"], patterns: [], symbols: ["crescent","star"], ext: "svg" },
    { code: "ec", name: "Ecuador", group: "south-america", colors: ["yellow","blue","red"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "ee", name: "Estonia", group: "europe", colors: ["blue","black","white"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "eg", name: "Egypt", group: "africa", colors: ["red","white","black"], patterns: ["tricolor-horizontal","pan-arab"], symbols: ["eagle"], ext: "svg" },
    { code: "er", name: "Eritrea", group: "africa", colors: ["red","green","blue"], patterns: ["triangle"], symbols: ["emblem"], ext: "svg" },
    { code: "es", name: "Spain", group: "europe", colors: ["red","yellow"], patterns: ["stripes-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "et", name: "Ethiopia", group: "africa", colors: ["green","yellow","red"], patterns: ["tricolor-horizontal","circle","pan-african"], symbols: ["star"], ext: "svg" },
    { code: "fi", name: "Finland", group: "europe", colors: ["white","blue"], patterns: ["nordic-cross"], symbols: [], ext: "svg" },
    { code: "fj", name: "Fiji", group: "oceania", colors: ["blue","red","white"], patterns: ["canton"], symbols: ["union-jack","shield"], ext: "svg" },
    { code: "fm", name: "Micronesia", group: "oceania", colors: ["blue","white"], patterns: [], symbols: ["stars"], ext: "svg" },
    { code: "fr", name: "France", group: "europe", colors: ["blue","white","red"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "ga", name: "Gabon", group: "africa", colors: ["green","yellow","blue"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "gb", name: "United Kingdom", group: "europe", colors: ["red","white","blue"], patterns: ["cross"], symbols: ["union-jack"], ext: "svg" },
    { code: "gd", name: "Grenada", group: "north-america", colors: ["red","yellow","green"], patterns: ["circle"], symbols: ["stars","emblem"], ext: "svg" },
    { code: "ge", name: "Georgia", group: "asia", colors: ["white","red"], patterns: ["cross"], symbols: [], ext: "svg" },
    { code: "gh", name: "Ghana", group: "africa", colors: ["red","yellow","green"], patterns: ["tricolor-horizontal","pan-african"], symbols: ["star"], ext: "svg" },
    { code: "gm", name: "Gambia", group: "africa", colors: ["red","blue","green","white"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "gn", name: "Guinea", group: "africa", colors: ["red","yellow","green"], patterns: ["tricolor-vertical","pan-african"], symbols: [], ext: "svg" },
    { code: "gq", name: "Equatorial Guinea", group: "africa", colors: ["green","white","red","blue"], patterns: ["tricolor-horizontal","triangle"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "gr", name: "Greece", group: "europe", colors: ["blue","white"], patterns: ["stripes-horizontal","cross","canton"], symbols: [], ext: "svg" },
    { code: "gt", name: "Guatemala", group: "north-america", colors: ["blue","white"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "gw", name: "Guinea-Bissau", group: "africa", colors: ["red","yellow","green"], patterns: ["pan-african"], symbols: ["star"], ext: "svg" },
    { code: "gy", name: "Guyana", group: "south-america", colors: ["green","yellow","red","black","white"], patterns: ["triangle"], symbols: [], ext: "svg" },
    { code: "hn", name: "Honduras", group: "north-america", colors: ["blue","white"], patterns: ["stripes-horizontal"], symbols: ["stars"], ext: "svg" },
    { code: "hr", name: "Croatia", group: "europe", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "ht", name: "Haiti", group: "north-america", colors: ["blue","red"], patterns: ["bicolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "hu", name: "Hungary", group: "europe", colors: ["red","white","green"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "id", name: "Indonesia", group: "asia", colors: ["red","white"], patterns: ["bicolor-horizontal"], symbols: [], ext: "svg" },
    { code: "ie", name: "Ireland", group: "europe", colors: ["green","white","orange"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "il", name: "Israel", group: "asia", colors: ["blue","white"], patterns: ["stripes-horizontal"], symbols: ["star"], ext: "svg" },
    { code: "in", name: "India", group: "asia", colors: ["orange","white","green"], patterns: ["tricolor-horizontal","circle"], symbols: ["wheel"], ext: "svg" },
    { code: "iq", name: "Iraq", group: "asia", colors: ["red","white","black","green"], patterns: ["tricolor-horizontal","pan-arab"], symbols: [], ext: "svg" },
    { code: "ir", name: "Iran", group: "asia", colors: ["green","white","red"], patterns: ["tricolor-horizontal"], symbols: ["emblem"], ext: "svg" },
    { code: "is", name: "Iceland", group: "europe", colors: ["blue","white","red"], patterns: ["nordic-cross"], symbols: [], ext: "svg" },
    { code: "it", name: "Italy", group: "europe", colors: ["green","white","red"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "jm", name: "Jamaica", group: "north-america", colors: ["green","yellow","black"], patterns: ["diagonal","cross"], symbols: [], ext: "svg" },
    { code: "jo", name: "Jordan", group: "asia", colors: ["black","white","green","red"], patterns: ["triangle","pan-arab"], symbols: ["star"], ext: "svg" },
    { code: "jp", name: "Japan", group: "asia", colors: ["white","red"], patterns: ["circle"], symbols: [], ext: "svg" },
    { code: "ke", name: "Kenya", group: "africa", colors: ["black","red","green","white"], patterns: ["stripes-horizontal"], symbols: ["shield","weapon"], ext: "svg" },
    { code: "kg", name: "Kyrgyzstan", group: "asia", colors: ["red","yellow"], patterns: ["circle"], symbols: ["sun"], ext: "svg" },
    { code: "kh", name: "Cambodia", group: "asia", colors: ["blue","red"], patterns: ["stripes-horizontal"], symbols: ["emblem"], ext: "svg" },
    { code: "ki", name: "Kiribati", group: "oceania", colors: ["red","blue","white","yellow"], patterns: ["stripes-horizontal"], symbols: ["sun","bird"], ext: "svg" },
    { code: "km", name: "Comoros", group: "africa", colors: ["green","yellow","white","blue","red"], patterns: ["triangle"], symbols: ["crescent","stars"], ext: "svg" },
    { code: "kn", name: "Saint Kitts and Nevis", group: "north-america", colors: ["green","red","black","yellow","white"], patterns: ["diagonal"], symbols: ["stars"], ext: "svg" },
    { code: "kp", name: "North Korea", group: "asia", colors: ["blue","red","white"], patterns: ["stripes-horizontal","circle"], symbols: ["star"], ext: "svg" },
    { code: "kr", name: "South Korea", group: "asia", colors: ["white","red","blue"], patterns: ["circle"], symbols: ["emblem"], ext: "svg" },
    { code: "ks", name: "Kosovo", group: "europe", colors: ["blue","yellow","white"], patterns: [], symbols: ["stars","emblem"], ext: "svg" },
    { code: "kw", name: "Kuwait", group: "asia", colors: ["green","white","red","black"], patterns: ["stripes-horizontal","triangle","pan-arab"], symbols: [], ext: "svg" },
    { code: "kz", name: "Kazakhstan", group: "asia", colors: ["blue","yellow"], patterns: [], symbols: ["sun","eagle","pattern"], ext: "svg" },
    { code: "la", name: "Laos", group: "asia", colors: ["red","blue","white"], patterns: ["stripes-horizontal","circle"], symbols: [], ext: "svg" },
    { code: "lb", name: "Lebanon", group: "asia", colors: ["red","white","green"], patterns: ["stripes-horizontal"], symbols: ["tree"], ext: "svg" },
    { code: "lc", name: "Saint Lucia", group: "north-america", colors: ["blue","yellow","black","white"], patterns: ["triangle"], symbols: [], ext: "svg" },
    { code: "li", name: "Liechtenstein", group: "europe", colors: ["blue","red"], patterns: ["bicolor-horizontal"], symbols: ["emblem"], ext: "svg" },
    { code: "lk", name: "Sri Lanka", group: "asia", colors: ["yellow","red","green","orange"], patterns: [], symbols: ["animal","emblem"], ext: "svg" },
    { code: "lr", name: "Liberia", group: "africa", colors: ["red","white","blue"], patterns: ["stripes-horizontal","canton"], symbols: ["star"], ext: "svg" },
    { code: "ls", name: "Lesotho", group: "africa", colors: ["blue","white","green"], patterns: ["tricolor-horizontal"], symbols: ["emblem"], ext: "svg" },
    { code: "lt", name: "Lithuania", group: "europe", colors: ["yellow","green","red"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "lu", name: "Luxembourg", group: "europe", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "lv", name: "Latvia", group: "europe", colors: ["red","white"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "ly", name: "Libya", group: "africa", colors: ["red","black","green","white"], patterns: ["stripes-horizontal"], symbols: ["crescent","star"], ext: "svg" },
    { code: "ma", name: "Morocco", group: "africa", colors: ["red","green"], patterns: [], symbols: ["star"], ext: "svg" },
    { code: "mc", name: "Monaco", group: "europe", colors: ["red","white"], patterns: ["bicolor-horizontal"], symbols: [], ext: "svg" },
    { code: "md", name: "Moldova", group: "europe", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms","eagle"], ext: "svg" },
    { code: "me", name: "Montenegro", group: "europe", colors: ["red","yellow"], patterns: [], symbols: ["eagle","coat-of-arms"], ext: "svg" },
    { code: "mg", name: "Madagascar", group: "africa", colors: ["white","red","green"], patterns: [], symbols: [], ext: "svg" },
    { code: "mh", name: "Marshall Islands", group: "oceania", colors: ["blue","white","orange"], patterns: ["diagonal"], symbols: ["star"], ext: "svg" },
    { code: "mk", name: "North Macedonia", group: "europe", colors: ["red","yellow"], patterns: [], symbols: ["sun"], ext: "svg" },
    { code: "ml", name: "Mali", group: "africa", colors: ["green","yellow","red"], patterns: ["tricolor-vertical","pan-african"], symbols: [], ext: "svg" },
    { code: "mm", name: "Myanmar", group: "asia", colors: ["yellow","green","red"], patterns: ["tricolor-horizontal"], symbols: ["star"], ext: "svg" },
    { code: "mn", name: "Mongolia", group: "asia", colors: ["red","blue"], patterns: [], symbols: ["emblem"], ext: "svg" },
    { code: "mr", name: "Mauritania", group: "africa", colors: ["green","red","yellow"], patterns: [], symbols: ["crescent","star"], ext: "svg" },
    { code: "mt", name: "Malta", group: "europe", colors: ["white","red"], patterns: ["bicolor-vertical","cross"], symbols: [], ext: "svg" },
    { code: "mu", name: "Mauritius", group: "africa", colors: ["red","blue","yellow","green"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "mv", name: "Maldives", group: "asia", colors: ["red","green","white"], patterns: [], symbols: ["crescent"], ext: "svg" },
    { code: "mw", name: "Malawi", group: "africa", colors: ["black","red","green"], patterns: ["tricolor-horizontal"], symbols: ["sun"], ext: "svg" },
    { code: "mx", name: "Mexico", group: "north-america", colors: ["green","white","red"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms","eagle"], ext: "svg" },
    { code: "my", name: "Malaysia", group: "asia", colors: ["red","white","blue","yellow"], patterns: ["stripes-horizontal","canton"], symbols: ["crescent","star"], ext: "svg" },
    { code: "mz", name: "Mozambique", group: "africa", colors: ["green","black","yellow","white","red"], patterns: ["triangle"], symbols: ["star","weapon"], ext: "svg" },
    { code: "na", name: "Namibia", group: "africa", colors: ["blue","red","green","white","yellow"], patterns: ["diagonal"], symbols: ["sun"], ext: "svg" },
    { code: "ne", name: "Niger", group: "africa", colors: ["orange","white","green"], patterns: ["tricolor-horizontal","circle"], symbols: [], ext: "svg" },
    { code: "ng", name: "Nigeria", group: "africa", colors: ["green","white"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "ni", name: "Nicaragua", group: "north-america", colors: ["blue","white"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "nl", name: "Netherlands", group: "europe", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "no", name: "Norway", group: "europe", colors: ["red","white","blue"], patterns: ["nordic-cross"], symbols: [], ext: "svg" },
    { code: "np", name: "Nepal", group: "asia", colors: ["red","blue","white"], patterns: ["triangle"], symbols: ["sun","crescent"], ext: "svg" },
    { code: "nr", name: "Nauru", group: "oceania", colors: ["blue","yellow","white"], patterns: ["stripes-horizontal"], symbols: ["star"], ext: "svg" },
    { code: "nz", name: "New Zealand", group: "oceania", colors: ["blue","red","white"], patterns: ["canton"], symbols: ["union-jack","stars"], ext: "svg" },
    { code: "om", name: "Oman", group: "asia", colors: ["red","white","green"], patterns: [], symbols: ["emblem"], ext: "svg" },
    { code: "pa", name: "Panama", group: "north-america", colors: ["white","red","blue"], patterns: ["quarters"], symbols: ["stars"], ext: "svg" },
    { code: "pe", name: "Peru", group: "south-america", colors: ["red","white"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "pg", name: "Papua New Guinea", group: "oceania", colors: ["red","black"], patterns: ["diagonal"], symbols: ["bird","stars"], ext: "svg" },
    { code: "ph", name: "Philippines", group: "asia", colors: ["blue","red","white"], patterns: ["triangle"], symbols: ["sun","stars"], ext: "svg" },
    { code: "pk", name: "Pakistan", group: "asia", colors: ["green","white"], patterns: [], symbols: ["crescent","star"], ext: "svg" },
    { code: "pl", name: "Poland", group: "europe", colors: ["white","red"], patterns: ["bicolor-horizontal"], symbols: [], ext: "svg" },
    { code: "ps", name: "Palestine", group: "asia", colors: ["black","white","green","red"], patterns: ["triangle","pan-arab"], symbols: [], ext: "svg" },
    { code: "pt", name: "Portugal", group: "europe", colors: ["green","red"], patterns: ["bicolor-vertical","circle"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "pw", name: "Palau", group: "oceania", colors: ["blue","yellow"], patterns: ["circle"], symbols: [], ext: "svg" },
    { code: "py", name: "Paraguay", group: "south-america", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "qa", name: "Qatar", group: "asia", colors: ["white","red"], patterns: ["chevron"], symbols: [], ext: "svg" },
    { code: "ro", name: "Romania", group: "europe", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "rs", name: "Serbia", group: "europe", colors: ["red","blue","white"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "ru", name: "Russia", group: "europe", colors: ["white","blue","red"], patterns: ["tricolor-horizontal","pan-slavic"], symbols: [], ext: "svg" },
    { code: "rw", name: "Rwanda", group: "africa", colors: ["blue","yellow","green"], patterns: ["tricolor-horizontal"], symbols: ["sun"], ext: "svg" },
    { code: "sa", name: "Saudi Arabia", group: "asia", colors: ["green","white"], patterns: [], symbols: ["emblem","weapon"], ext: "svg" },
    { code: "sb", name: "Solomon Islands", group: "oceania", colors: ["blue","green","yellow"], patterns: ["diagonal"], symbols: ["stars"], ext: "svg" },
    { code: "sc", name: "Seychelles", group: "africa", colors: ["blue","yellow","red","white","green"], patterns: ["diagonal"], symbols: [], ext: "svg" },
    { code: "sd", name: "Sudan", group: "africa", colors: ["red","white","black","green"], patterns: ["tricolor-horizontal","triangle","pan-arab"], symbols: [], ext: "svg" },
    { code: "se", name: "Sweden", group: "europe", colors: ["blue","yellow"], patterns: ["nordic-cross"], symbols: [], ext: "svg" },
    { code: "sg", name: "Singapore", group: "asia", colors: ["red","white"], patterns: ["bicolor-horizontal"], symbols: ["crescent","stars"], ext: "svg" },
    { code: "si", name: "Slovenia", group: "europe", colors: ["white","blue","red"], patterns: ["tricolor-horizontal","pan-slavic"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "sk", name: "Slovakia", group: "europe", colors: ["white","blue","red"], patterns: ["tricolor-horizontal","cross","pan-slavic"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "sl", name: "Sierra Leone", group: "africa", colors: ["green","white","blue"], patterns: ["tricolor-horizontal"], symbols: [], ext: "svg" },
    { code: "sm", name: "San Marino", group: "europe", colors: ["white","blue"], patterns: ["bicolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "sn", name: "Senegal", group: "africa", colors: ["green","yellow","red"], patterns: ["tricolor-vertical","pan-african"], symbols: ["star"], ext: "svg" },
    { code: "so", name: "Somalia", group: "africa", colors: ["blue","white"], patterns: [], symbols: ["star"], ext: "svg" },
    { code: "sr", name: "Suriname", group: "south-america", colors: ["green","white","red"], patterns: ["stripes-horizontal"], symbols: ["star"], ext: "svg" },
    { code: "ss", name: "South Sudan", group: "africa", colors: ["black","red","green","white","blue"], patterns: ["stripes-horizontal","triangle"], symbols: ["star"], ext: "svg" },
    { code: "st", name: "Sao Tome and Principe", group: "africa", colors: ["green","yellow","black","red"], patterns: ["tricolor-horizontal","triangle"], symbols: ["stars"], ext: "svg" },
    { code: "sv", name: "El Salvador", group: "north-america", colors: ["blue","white"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], ext: "svg" },
    { code: "sy", name: "Syria", group: "asia", colors: ["red","white","black","green"], patterns: ["tricolor-horizontal","pan-arab"], symbols: ["stars"], ext: "svg" },
    { code: "sz", name: "Eswatini", group: "africa", colors: ["blue","yellow","red"], patterns: ["stripes-horizontal"], symbols: ["shield","weapon"], ext: "svg" },
    { code: "td", name: "Chad", group: "africa", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "tg", name: "Togo", group: "africa", colors: ["green","yellow","red","white"], patterns: ["stripes-horizontal","canton"], symbols: ["star"], ext: "svg" },
    { code: "th", name: "Thailand", group: "asia", colors: ["red","white","blue"], patterns: ["stripes-horizontal"], symbols: [], ext: "svg" },
    { code: "tj", name: "Tajikistan", group: "asia", colors: ["red","white","green"], patterns: ["tricolor-horizontal"], symbols: ["emblem"], ext: "svg" },
    { code: "tl", name: "Timor-Leste", group: "asia", colors: ["red","yellow","black"], patterns: ["triangle"], symbols: ["star"], ext: "svg" },
    { code: "tm", name: "Turkmenistan", group: "asia", colors: ["green","red","white"], patterns: [], symbols: ["crescent","stars","pattern"], ext: "svg" },
    { code: "tn", name: "Tunisia", group: "africa", colors: ["red","white"], patterns: ["circle"], symbols: ["crescent","star"], ext: "svg" },
    { code: "to", name: "Tonga", group: "oceania", colors: ["red","white"], patterns: ["cross","canton"], symbols: [], ext: "svg" },
    { code: "tr", name: "Turkey", group: "asia", colors: ["red","white"], patterns: [], symbols: ["crescent","star"], ext: "svg" },
    { code: "tt", name: "Trinidad and Tobago", group: "north-america", colors: ["red","white","black"], patterns: ["diagonal"], symbols: [], ext: "svg" },
    { code: "tv", name: "Tuvalu", group: "oceania", colors: ["blue","yellow","red","white"], patterns: ["canton"], symbols: ["union-jack","stars"], ext: "svg" },
    { code: "tw", name: "Taiwan", group: "asia", colors: ["red","blue","white"], patterns: ["canton"], symbols: ["sun"], ext: "svg" },
    { code: "tz", name: "Tanzania", group: "africa", colors: ["green","blue","yellow","black"], patterns: ["diagonal"], symbols: [], ext: "svg" },
    { code: "ua", name: "Ukraine", group: "europe", colors: ["blue","yellow"], patterns: ["bicolor-horizontal"], symbols: [], ext: "svg" },
    { code: "ug", name: "Uganda", group: "africa", colors: ["black","yellow","red"], patterns: ["stripes-horizontal","circle"], symbols: ["bird"], ext: "svg" },
    { code: "us", name: "United States", group: "north-america", colors: ["red","white","blue"], patterns: ["stripes-horizontal","canton"], symbols: ["stars"], ext: "svg" },
    { code: "uy", name: "Uruguay", group: "south-america", colors: ["white","blue"], patterns: ["stripes-horizontal","canton"], symbols: ["sun"], ext: "svg" },
    { code: "uz", name: "Uzbekistan", group: "asia", colors: ["blue","white","green","red"], patterns: ["stripes-horizontal"], symbols: ["crescent","stars"], ext: "svg" },
    { code: "va", name: "Vatican City", group: "europe", colors: ["yellow","white"], patterns: ["bicolor-vertical"], symbols: ["emblem"], ext: "svg" },
    { code: "vc", name: "Saint Vincent and the Grenadines", group: "north-america", colors: ["blue","yellow","green"], patterns: ["tricolor-vertical"], symbols: [], ext: "svg" },
    { code: "ve", name: "Venezuela", group: "south-america", colors: ["yellow","blue","red"], patterns: ["tricolor-horizontal"], symbols: ["stars","coat-of-arms"], ext: "svg" },
    { code: "vn", name: "Vietnam", group: "asia", colors: ["red","yellow"], patterns: [], symbols: ["star"], ext: "svg" },
    { code: "vu", name: "Vanuatu", group: "oceania", colors: ["red","green","black","yellow"], patterns: ["triangle"], symbols: ["emblem"], ext: "svg" },
    { code: "ws", name: "Samoa", group: "oceania", colors: ["red","blue","white"], patterns: ["canton"], symbols: ["stars"], ext: "svg" },
    { code: "ye", name: "Yemen", group: "asia", colors: ["red","white","black"], patterns: ["tricolor-horizontal","pan-arab"], symbols: [], ext: "svg" },
    { code: "za", name: "South Africa", group: "africa", colors: ["red","blue","green","yellow","black","white"], patterns: ["chevron","triangle"], symbols: [], ext: "svg" },
    { code: "zm", name: "Zambia", group: "africa", colors: ["green","red","orange","black"], patterns: [], symbols: ["eagle"], ext: "svg" },
    { code: "zw", name: "Zimbabwe", group: "africa", colors: ["green","yellow","red","black","white"], patterns: ["stripes-horizontal","triangle"], symbols: ["star","bird"], ext: "svg" },
  ],
};
