import type { Continent } from "./enums.js";

export interface Flag {
  code: string;
  name: string;
  colors: string[];
  patterns: string[];
  symbols: string[];
  continent: Continent;
}

export const flags: Flag[] = [
  { code: "ad", name: "Andorra", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "ae", name: "United Arab Emirates", colors: ["red","green","white","black"], patterns: ["stripes-horizontal","pan-arab"], symbols: [], continent: "asia" },
  { code: "af", name: "Afghanistan", colors: ["black","red","green"], patterns: ["tricolor-vertical"], symbols: ["emblem"], continent: "asia" },
  { code: "ag", name: "Antigua and Barbuda", colors: ["red","black","blue","yellow"], patterns: ["triangle"], symbols: ["sun"], continent: "north-america" },
  { code: "al", name: "Albania", colors: ["red","black"], patterns: [], symbols: ["eagle"], continent: "europe" },
  { code: "am", name: "Armenia", colors: ["red","blue","orange"], patterns: ["tricolor-horizontal"], symbols: [], continent: "asia" },
  { code: "ao", name: "Angola", colors: ["red","black","yellow"], patterns: ["bicolor-horizontal"], symbols: ["emblem","star"], continent: "africa" },
  { code: "ar", name: "Argentina", colors: ["blue","white"], patterns: ["stripes-horizontal"], symbols: ["sun"], continent: "south-america" },
  { code: "at", name: "Austria", colors: ["red","white"], patterns: ["stripes-horizontal"], symbols: [], continent: "europe" },
  { code: "au", name: "Australia", colors: ["blue","red","white"], patterns: ["canton"], symbols: ["union-jack","stars"], continent: "oceania" },
  { code: "az", name: "Azerbaijan", colors: ["blue","red","green"], patterns: ["tricolor-horizontal"], symbols: ["crescent","star"], continent: "asia" },
  { code: "ba", name: "Bosnia and Herzegovina", colors: ["blue","yellow","white"], patterns: ["triangle"], symbols: ["stars"], continent: "europe" },
  { code: "bb", name: "Barbados", colors: ["blue","yellow"], patterns: ["tricolor-vertical"], symbols: ["trident"], continent: "north-america" },
  { code: "bd", name: "Bangladesh", colors: ["green","red"], patterns: ["circle"], symbols: [], continent: "asia" },
  { code: "be", name: "Belgium", colors: ["black","yellow","red"], patterns: ["tricolor-vertical"], symbols: [], continent: "europe" },
  { code: "bf", name: "Burkina Faso", colors: ["red","green"], patterns: ["bicolor-horizontal","pan-african"], symbols: ["star"], continent: "africa" },
  { code: "bg", name: "Bulgaria", colors: ["white","green","red"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "bh", name: "Bahrain", colors: ["red","white"], patterns: ["chevron"], symbols: [], continent: "asia" },
  { code: "bi", name: "Burundi", colors: ["red","white","green"], patterns: ["diagonal","circle"], symbols: ["stars"], continent: "africa" },
  { code: "bj", name: "Benin", colors: ["green","yellow","red"], patterns: ["pan-african"], symbols: [], continent: "africa" },
  { code: "bn", name: "Brunei", colors: ["yellow","white","black"], patterns: ["diagonal"], symbols: ["emblem"], continent: "asia" },
  { code: "bo", name: "Bolivia", colors: ["red","yellow","green"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "south-america" },
  { code: "br", name: "Brazil", colors: ["green","yellow","blue","white"], patterns: ["circle"], symbols: ["stars"], continent: "south-america" },
  { code: "bs", name: "Bahamas", colors: ["blue","yellow","black"], patterns: ["stripes-horizontal","triangle"], symbols: [], continent: "north-america" },
  { code: "bt", name: "Bhutan", colors: ["orange","yellow"], patterns: ["diagonal"], symbols: ["dragon"], continent: "asia" },
  { code: "bw", name: "Botswana", colors: ["blue","white","black"], patterns: ["stripes-horizontal"], symbols: [], continent: "africa" },
  { code: "by", name: "Belarus", colors: ["red","green","white"], patterns: [], symbols: ["pattern"], continent: "europe" },
  { code: "bz", name: "Belize", colors: ["blue","red","white"], patterns: ["circle"], symbols: ["coat-of-arms"], continent: "north-america" },
  { code: "ca", name: "Canada", colors: ["red","white"], patterns: [], symbols: ["tree"], continent: "north-america" },
  { code: "cd", name: "Democratic Republic of the Congo", colors: ["blue","red","yellow"], patterns: ["diagonal"], symbols: ["star"], continent: "africa" },
  { code: "cf", name: "Central African Republic", colors: ["blue","white","green","yellow","red"], patterns: ["stripes-horizontal"], symbols: ["star"], continent: "africa" },
  { code: "cg", name: "Republic of the Congo", colors: ["green","yellow","red"], patterns: ["diagonal"], symbols: [], continent: "africa" },
  { code: "ch", name: "Switzerland", colors: ["red","white"], patterns: ["cross"], symbols: [], continent: "europe" },
  { code: "ci", name: "Ivory Coast", colors: ["orange","white","green"], patterns: ["tricolor-vertical"], symbols: [], continent: "africa" },
  { code: "cl", name: "Chile", colors: ["red","white","blue"], patterns: ["canton"], symbols: ["star"], continent: "south-america" },
  { code: "cm", name: "Cameroon", colors: ["green","red","yellow"], patterns: ["tricolor-vertical","pan-african"], symbols: ["star"], continent: "africa" },
  { code: "cn", name: "China", colors: ["red","yellow"], patterns: [], symbols: ["stars"], continent: "asia" },
  { code: "co", name: "Colombia", colors: ["yellow","blue","red"], patterns: ["tricolor-horizontal"], symbols: [], continent: "south-america" },
  { code: "cr", name: "Costa Rica", colors: ["blue","white","red"], patterns: ["stripes-horizontal"], symbols: [], continent: "north-america" },
  { code: "cu", name: "Cuba", colors: ["blue","white","red"], patterns: ["stripes-horizontal","triangle"], symbols: ["star"], continent: "north-america" },
  { code: "cv", name: "Cape Verde", colors: ["blue","white","red"], patterns: ["stripes-horizontal","circle"], symbols: ["stars"], continent: "africa" },
  { code: "cy", name: "Cyprus", colors: ["white","orange"], patterns: [], symbols: ["emblem"], continent: "europe" },
  { code: "cz", name: "Czech Republic", colors: ["white","red","blue"], patterns: ["triangle"], symbols: [], continent: "europe" },
  { code: "de", name: "Germany", colors: ["black","red","yellow"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "dj", name: "Djibouti", colors: ["blue","green","white"], patterns: ["triangle"], symbols: ["star"], continent: "africa" },
  { code: "dk", name: "Denmark", colors: ["red","white"], patterns: ["nordic-cross"], symbols: [], continent: "europe" },
  { code: "dm", name: "Dominica", colors: ["green","red","yellow","black","white"], patterns: ["cross","circle"], symbols: ["bird"], continent: "north-america" },
  { code: "do", name: "Dominican Republic", colors: ["red","blue","white"], patterns: ["cross"], symbols: ["coat-of-arms"], continent: "north-america" },
  { code: "dz", name: "Algeria", colors: ["green","white","red"], patterns: [], symbols: ["crescent","star"], continent: "africa" },
  { code: "ec", name: "Ecuador", colors: ["yellow","blue","red"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "south-america" },
  { code: "ee", name: "Estonia", colors: ["blue","black","white"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "eg", name: "Egypt", colors: ["red","white","black"], patterns: ["tricolor-horizontal","pan-arab"], symbols: ["eagle"], continent: "africa" },
  { code: "er", name: "Eritrea", colors: ["red","green","blue"], patterns: ["triangle"], symbols: ["emblem"], continent: "africa" },
  { code: "es", name: "Spain", colors: ["red","yellow"], patterns: ["stripes-horizontal"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "et", name: "Ethiopia", colors: ["green","yellow","red"], patterns: ["tricolor-horizontal","circle","pan-african"], symbols: ["star"], continent: "africa" },
  { code: "fi", name: "Finland", colors: ["white","blue"], patterns: ["nordic-cross"], symbols: [], continent: "europe" },
  { code: "fj", name: "Fiji", colors: ["blue","red","white"], patterns: ["canton"], symbols: ["union-jack","shield"], continent: "oceania" },
  { code: "fm", name: "Micronesia", colors: ["blue","white"], patterns: [], symbols: ["stars"], continent: "oceania" },
  { code: "fr", name: "France", colors: ["blue","white","red"], patterns: ["tricolor-vertical"], symbols: [], continent: "europe" },
  { code: "ga", name: "Gabon", colors: ["green","yellow","blue"], patterns: ["tricolor-horizontal"], symbols: [], continent: "africa" },
  { code: "gb", name: "United Kingdom", colors: ["red","white","blue"], patterns: ["cross"], symbols: ["union-jack"], continent: "europe" },
  { code: "gd", name: "Grenada", colors: ["red","yellow","green"], patterns: ["circle"], symbols: ["stars","emblem"], continent: "north-america" },
  { code: "ge", name: "Georgia", colors: ["white","red"], patterns: ["cross"], symbols: [], continent: "asia" },
  { code: "gh", name: "Ghana", colors: ["red","yellow","green"], patterns: ["tricolor-horizontal","pan-african"], symbols: ["star"], continent: "africa" },
  { code: "gm", name: "Gambia", colors: ["red","blue","green","white"], patterns: ["stripes-horizontal"], symbols: [], continent: "africa" },
  { code: "gn", name: "Guinea", colors: ["red","yellow","green"], patterns: ["tricolor-vertical","pan-african"], symbols: [], continent: "africa" },
  { code: "gq", name: "Equatorial Guinea", colors: ["green","white","red","blue"], patterns: ["tricolor-horizontal","triangle"], symbols: ["coat-of-arms"], continent: "africa" },
  { code: "gr", name: "Greece", colors: ["blue","white"], patterns: ["stripes-horizontal","cross","canton"], symbols: [], continent: "europe" },
  { code: "gt", name: "Guatemala", colors: ["blue","white"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms"], continent: "north-america" },
  { code: "gw", name: "Guinea-Bissau", colors: ["red","yellow","green"], patterns: ["pan-african"], symbols: ["star"], continent: "africa" },
  { code: "gy", name: "Guyana", colors: ["green","yellow","red","black","white"], patterns: ["triangle"], symbols: [], continent: "south-america" },
  { code: "hn", name: "Honduras", colors: ["blue","white"], patterns: ["stripes-horizontal"], symbols: ["stars"], continent: "north-america" },
  { code: "hr", name: "Croatia", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "ht", name: "Haiti", colors: ["blue","red"], patterns: ["bicolor-horizontal"], symbols: ["coat-of-arms"], continent: "north-america" },
  { code: "hu", name: "Hungary", colors: ["red","white","green"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "id", name: "Indonesia", colors: ["red","white"], patterns: ["bicolor-horizontal"], symbols: [], continent: "asia" },
  { code: "ie", name: "Ireland", colors: ["green","white","orange"], patterns: ["tricolor-vertical"], symbols: [], continent: "europe" },
  { code: "il", name: "Israel", colors: ["blue","white"], patterns: ["stripes-horizontal"], symbols: ["star"], continent: "asia" },
  { code: "in", name: "India", colors: ["orange","white","green"], patterns: ["tricolor-horizontal","circle"], symbols: ["wheel"], continent: "asia" },
  { code: "iq", name: "Iraq", colors: ["red","white","black","green"], patterns: ["tricolor-horizontal","pan-arab"], symbols: [], continent: "asia" },
  { code: "ir", name: "Iran", colors: ["green","white","red"], patterns: ["tricolor-horizontal"], symbols: ["emblem"], continent: "asia" },
  { code: "is", name: "Iceland", colors: ["blue","white","red"], patterns: ["nordic-cross"], symbols: [], continent: "europe" },
  { code: "it", name: "Italy", colors: ["green","white","red"], patterns: ["tricolor-vertical"], symbols: [], continent: "europe" },
  { code: "jm", name: "Jamaica", colors: ["green","yellow","black"], patterns: ["diagonal","cross"], symbols: [], continent: "north-america" },
  { code: "jo", name: "Jordan", colors: ["black","white","green","red"], patterns: ["triangle","pan-arab"], symbols: ["star"], continent: "asia" },
  { code: "jp", name: "Japan", colors: ["white","red"], patterns: ["circle"], symbols: [], continent: "asia" },
  { code: "ke", name: "Kenya", colors: ["black","red","green","white"], patterns: ["stripes-horizontal"], symbols: ["shield","weapon"], continent: "africa" },
  { code: "kg", name: "Kyrgyzstan", colors: ["red","yellow"], patterns: ["circle"], symbols: ["sun"], continent: "asia" },
  { code: "kh", name: "Cambodia", colors: ["blue","red"], patterns: ["stripes-horizontal"], symbols: ["emblem"], continent: "asia" },
  { code: "ki", name: "Kiribati", colors: ["red","blue","white","yellow"], patterns: ["stripes-horizontal"], symbols: ["sun","bird"], continent: "oceania" },
  { code: "km", name: "Comoros", colors: ["green","yellow","white","blue","red"], patterns: ["triangle"], symbols: ["crescent","stars"], continent: "africa" },
  { code: "kn", name: "Saint Kitts and Nevis", colors: ["green","red","black","yellow","white"], patterns: ["diagonal"], symbols: ["stars"], continent: "north-america" },
  { code: "kp", name: "North Korea", colors: ["blue","red","white"], patterns: ["stripes-horizontal","circle"], symbols: ["star"], continent: "asia" },
  { code: "kr", name: "South Korea", colors: ["white","red","blue"], patterns: ["circle"], symbols: ["emblem"], continent: "asia" },
  { code: "ks", name: "Kosovo", colors: ["blue","yellow","white"], patterns: [], symbols: ["stars","emblem"], continent: "europe" },
  { code: "kw", name: "Kuwait", colors: ["green","white","red","black"], patterns: ["stripes-horizontal","triangle","pan-arab"], symbols: [], continent: "asia" },
  { code: "kz", name: "Kazakhstan", colors: ["blue","yellow"], patterns: [], symbols: ["sun","eagle","pattern"], continent: "asia" },
  { code: "la", name: "Laos", colors: ["red","blue","white"], patterns: ["stripes-horizontal","circle"], symbols: [], continent: "asia" },
  { code: "lb", name: "Lebanon", colors: ["red","white","green"], patterns: ["stripes-horizontal"], symbols: ["tree"], continent: "asia" },
  { code: "lc", name: "Saint Lucia", colors: ["blue","yellow","black","white"], patterns: ["triangle"], symbols: [], continent: "north-america" },
  { code: "li", name: "Liechtenstein", colors: ["blue","red"], patterns: ["bicolor-horizontal"], symbols: ["emblem"], continent: "europe" },
  { code: "lk", name: "Sri Lanka", colors: ["yellow","red","green","orange"], patterns: [], symbols: ["animal","emblem"], continent: "asia" },
  { code: "lr", name: "Liberia", colors: ["red","white","blue"], patterns: ["stripes-horizontal","canton"], symbols: ["star"], continent: "africa" },
  { code: "ls", name: "Lesotho", colors: ["blue","white","green"], patterns: ["tricolor-horizontal"], symbols: ["emblem"], continent: "africa" },
  { code: "lt", name: "Lithuania", colors: ["yellow","green","red"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "lu", name: "Luxembourg", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "lv", name: "Latvia", colors: ["red","white"], patterns: ["stripes-horizontal"], symbols: [], continent: "europe" },
  { code: "ly", name: "Libya", colors: ["red","black","green","white"], patterns: ["stripes-horizontal"], symbols: ["crescent","star"], continent: "africa" },
  { code: "ma", name: "Morocco", colors: ["red","green"], patterns: [], symbols: ["star"], continent: "africa" },
  { code: "mc", name: "Monaco", colors: ["red","white"], patterns: ["bicolor-horizontal"], symbols: [], continent: "europe" },
  { code: "md", name: "Moldova", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms","eagle"], continent: "europe" },
  { code: "me", name: "Montenegro", colors: ["red","yellow"], patterns: [], symbols: ["eagle","coat-of-arms"], continent: "europe" },
  { code: "mg", name: "Madagascar", colors: ["white","red","green"], patterns: [], symbols: [], continent: "africa" },
  { code: "mh", name: "Marshall Islands", colors: ["blue","white","orange"], patterns: ["diagonal"], symbols: ["star"], continent: "oceania" },
  { code: "mk", name: "North Macedonia", colors: ["red","yellow"], patterns: [], symbols: ["sun"], continent: "europe" },
  { code: "ml", name: "Mali", colors: ["green","yellow","red"], patterns: ["tricolor-vertical","pan-african"], symbols: [], continent: "africa" },
  { code: "mm", name: "Myanmar", colors: ["yellow","green","red"], patterns: ["tricolor-horizontal"], symbols: ["star"], continent: "asia" },
  { code: "mn", name: "Mongolia", colors: ["red","blue"], patterns: [], symbols: ["emblem"], continent: "asia" },
  { code: "mr", name: "Mauritania", colors: ["green","red","yellow"], patterns: [], symbols: ["crescent","star"], continent: "africa" },
  { code: "mt", name: "Malta", colors: ["white","red"], patterns: ["bicolor-vertical","cross"], symbols: [], continent: "europe" },
  { code: "mu", name: "Mauritius", colors: ["red","blue","yellow","green"], patterns: ["stripes-horizontal"], symbols: [], continent: "africa" },
  { code: "mv", name: "Maldives", colors: ["red","green","white"], patterns: [], symbols: ["crescent"], continent: "asia" },
  { code: "mw", name: "Malawi", colors: ["black","red","green"], patterns: ["tricolor-horizontal"], symbols: ["sun"], continent: "africa" },
  { code: "mx", name: "Mexico", colors: ["green","white","red"], patterns: ["tricolor-vertical"], symbols: ["coat-of-arms","eagle"], continent: "north-america" },
  { code: "my", name: "Malaysia", colors: ["red","white","blue","yellow"], patterns: ["stripes-horizontal","canton"], symbols: ["crescent","star"], continent: "asia" },
  { code: "mz", name: "Mozambique", colors: ["green","black","yellow","white","red"], patterns: ["triangle"], symbols: ["star","weapon"], continent: "africa" },
  { code: "na", name: "Namibia", colors: ["blue","red","green","white","yellow"], patterns: ["diagonal"], symbols: ["sun"], continent: "africa" },
  { code: "ne", name: "Niger", colors: ["orange","white","green"], patterns: ["tricolor-horizontal","circle"], symbols: [], continent: "africa" },
  { code: "ng", name: "Nigeria", colors: ["green","white"], patterns: ["tricolor-vertical"], symbols: [], continent: "africa" },
  { code: "ni", name: "Nicaragua", colors: ["blue","white"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "north-america" },
  { code: "nl", name: "Netherlands", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: [], continent: "europe" },
  { code: "no", name: "Norway", colors: ["red","white","blue"], patterns: ["nordic-cross"], symbols: [], continent: "europe" },
  { code: "np", name: "Nepal", colors: ["red","blue","white"], patterns: ["triangle"], symbols: ["sun","crescent"], continent: "asia" },
  { code: "nr", name: "Nauru", colors: ["blue","yellow","white"], patterns: ["stripes-horizontal"], symbols: ["star"], continent: "oceania" },
  { code: "nz", name: "New Zealand", colors: ["blue","red","white"], patterns: ["canton"], symbols: ["union-jack","stars"], continent: "oceania" },
  { code: "om", name: "Oman", colors: ["red","white","green"], patterns: [], symbols: ["emblem"], continent: "asia" },
  { code: "pa", name: "Panama", colors: ["white","red","blue"], patterns: ["quarters"], symbols: ["stars"], continent: "north-america" },
  { code: "pe", name: "Peru", colors: ["red","white"], patterns: ["tricolor-vertical"], symbols: [], continent: "south-america" },
  { code: "pg", name: "Papua New Guinea", colors: ["red","black"], patterns: ["diagonal"], symbols: ["bird","stars"], continent: "oceania" },
  { code: "ph", name: "Philippines", colors: ["blue","red","white"], patterns: ["triangle"], symbols: ["sun","stars"], continent: "asia" },
  { code: "pk", name: "Pakistan", colors: ["green","white"], patterns: [], symbols: ["crescent","star"], continent: "asia" },
  { code: "pl", name: "Poland", colors: ["white","red"], patterns: ["bicolor-horizontal"], symbols: [], continent: "europe" },
  { code: "ps", name: "Palestine", colors: ["black","white","green","red"], patterns: ["triangle","pan-arab"], symbols: [], continent: "asia" },
  { code: "pt", name: "Portugal", colors: ["green","red"], patterns: ["bicolor-vertical","circle"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "pw", name: "Palau", colors: ["blue","yellow"], patterns: ["circle"], symbols: [], continent: "oceania" },
  { code: "py", name: "Paraguay", colors: ["red","white","blue"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "south-america" },
  { code: "qa", name: "Qatar", colors: ["white","red"], patterns: ["chevron"], symbols: [], continent: "asia" },
  { code: "ro", name: "Romania", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: [], continent: "europe" },
  { code: "rs", name: "Serbia", colors: ["red","blue","white"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "ru", name: "Russia", colors: ["white","blue","red"], patterns: ["tricolor-horizontal","pan-slavic"], symbols: [], continent: "europe" },
  { code: "rw", name: "Rwanda", colors: ["blue","yellow","green"], patterns: ["tricolor-horizontal"], symbols: ["sun"], continent: "africa" },
  { code: "sa", name: "Saudi Arabia", colors: ["green","white"], patterns: [], symbols: ["emblem","weapon"], continent: "asia" },
  { code: "sb", name: "Solomon Islands", colors: ["blue","green","yellow"], patterns: ["diagonal"], symbols: ["stars"], continent: "oceania" },
  { code: "sc", name: "Seychelles", colors: ["blue","yellow","red","white","green"], patterns: ["diagonal"], symbols: [], continent: "africa" },
  { code: "sd", name: "Sudan", colors: ["red","white","black","green"], patterns: ["tricolor-horizontal","triangle","pan-arab"], symbols: [], continent: "africa" },
  { code: "se", name: "Sweden", colors: ["blue","yellow"], patterns: ["nordic-cross"], symbols: [], continent: "europe" },
  { code: "sg", name: "Singapore", colors: ["red","white"], patterns: ["bicolor-horizontal"], symbols: ["crescent","stars"], continent: "asia" },
  { code: "si", name: "Slovenia", colors: ["white","blue","red"], patterns: ["tricolor-horizontal","pan-slavic"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "sk", name: "Slovakia", colors: ["white","blue","red"], patterns: ["tricolor-horizontal","cross","pan-slavic"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "sl", name: "Sierra Leone", colors: ["green","white","blue"], patterns: ["tricolor-horizontal"], symbols: [], continent: "africa" },
  { code: "sm", name: "San Marino", colors: ["white","blue"], patterns: ["bicolor-horizontal"], symbols: ["coat-of-arms"], continent: "europe" },
  { code: "sn", name: "Senegal", colors: ["green","yellow","red"], patterns: ["tricolor-vertical","pan-african"], symbols: ["star"], continent: "africa" },
  { code: "so", name: "Somalia", colors: ["blue","white"], patterns: [], symbols: ["star"], continent: "africa" },
  { code: "sr", name: "Suriname", colors: ["green","white","red"], patterns: ["stripes-horizontal"], symbols: ["star"], continent: "south-america" },
  { code: "ss", name: "South Sudan", colors: ["black","red","green","white","blue"], patterns: ["stripes-horizontal","triangle"], symbols: ["star"], continent: "africa" },
  { code: "st", name: "Sao Tome and Principe", colors: ["green","yellow","black","red"], patterns: ["tricolor-horizontal","triangle"], symbols: ["stars"], continent: "africa" },
  { code: "sv", name: "El Salvador", colors: ["blue","white"], patterns: ["tricolor-horizontal"], symbols: ["coat-of-arms"], continent: "north-america" },
  { code: "sy", name: "Syria", colors: ["red","white","black","green"], patterns: ["tricolor-horizontal","pan-arab"], symbols: ["stars"], continent: "asia" },
  { code: "sz", name: "Eswatini", colors: ["blue","yellow","red"], patterns: ["stripes-horizontal"], symbols: ["shield","weapon"], continent: "africa" },
  { code: "td", name: "Chad", colors: ["blue","yellow","red"], patterns: ["tricolor-vertical"], symbols: [], continent: "africa" },
  { code: "tg", name: "Togo", colors: ["green","yellow","red","white"], patterns: ["stripes-horizontal","canton"], symbols: ["star"], continent: "africa" },
  { code: "th", name: "Thailand", colors: ["red","white","blue"], patterns: ["stripes-horizontal"], symbols: [], continent: "asia" },
  { code: "tj", name: "Tajikistan", colors: ["red","white","green"], patterns: ["tricolor-horizontal"], symbols: ["emblem"], continent: "asia" },
  { code: "tl", name: "Timor-Leste", colors: ["red","yellow","black"], patterns: ["triangle"], symbols: ["star"], continent: "asia" },
  { code: "tm", name: "Turkmenistan", colors: ["green","red","white"], patterns: [], symbols: ["crescent","stars","pattern"], continent: "asia" },
  { code: "tn", name: "Tunisia", colors: ["red","white"], patterns: ["circle"], symbols: ["crescent","star"], continent: "africa" },
  { code: "to", name: "Tonga", colors: ["red","white"], patterns: ["cross","canton"], symbols: [], continent: "oceania" },
  { code: "tr", name: "Turkey", colors: ["red","white"], patterns: [], symbols: ["crescent","star"], continent: "asia" },
  { code: "tt", name: "Trinidad and Tobago", colors: ["red","white","black"], patterns: ["diagonal"], symbols: [], continent: "north-america" },
  { code: "tv", name: "Tuvalu", colors: ["blue","yellow","red","white"], patterns: ["canton"], symbols: ["union-jack","stars"], continent: "oceania" },
  { code: "tw", name: "Taiwan", colors: ["red","blue","white"], patterns: ["canton"], symbols: ["sun"], continent: "asia" },
  { code: "tz", name: "Tanzania", colors: ["green","blue","yellow","black"], patterns: ["diagonal"], symbols: [], continent: "africa" },
  { code: "ua", name: "Ukraine", colors: ["blue","yellow"], patterns: ["bicolor-horizontal"], symbols: [], continent: "europe" },
  { code: "ug", name: "Uganda", colors: ["black","yellow","red"], patterns: ["stripes-horizontal","circle"], symbols: ["bird"], continent: "africa" },
  { code: "us", name: "United States", colors: ["red","white","blue"], patterns: ["stripes-horizontal","canton"], symbols: ["stars"], continent: "north-america" },
  { code: "uy", name: "Uruguay", colors: ["white","blue"], patterns: ["stripes-horizontal","canton"], symbols: ["sun"], continent: "south-america" },
  { code: "uz", name: "Uzbekistan", colors: ["blue","white","green","red"], patterns: ["stripes-horizontal"], symbols: ["crescent","stars"], continent: "asia" },
  { code: "va", name: "Vatican City", colors: ["yellow","white"], patterns: ["bicolor-vertical"], symbols: ["emblem"], continent: "europe" },
  { code: "vc", name: "Saint Vincent and the Grenadines", colors: ["blue","yellow","green"], patterns: ["tricolor-vertical"], symbols: [], continent: "north-america" },
  { code: "ve", name: "Venezuela", colors: ["yellow","blue","red"], patterns: ["tricolor-horizontal"], symbols: ["stars","coat-of-arms"], continent: "south-america" },
  { code: "vn", name: "Vietnam", colors: ["red","yellow"], patterns: [], symbols: ["star"], continent: "asia" },
  { code: "vu", name: "Vanuatu", colors: ["red","green","black","yellow"], patterns: ["triangle"], symbols: ["emblem"], continent: "oceania" },
  { code: "ws", name: "Samoa", colors: ["red","blue","white"], patterns: ["canton"], symbols: ["stars"], continent: "oceania" },
  { code: "ye", name: "Yemen", colors: ["red","white","black"], patterns: ["tricolor-horizontal","pan-arab"], symbols: [], continent: "asia" },
  { code: "za", name: "South Africa", colors: ["red","blue","green","yellow","black","white"], patterns: ["chevron","triangle"], symbols: [], continent: "africa" },
  { code: "zm", name: "Zambia", colors: ["green","red","orange","black"], patterns: [], symbols: ["eagle"], continent: "africa" },
  { code: "zw", name: "Zimbabwe", colors: ["green","yellow","red","black","white"], patterns: ["stripes-horizontal","triangle"], symbols: ["star","bird"], continent: "africa" },
];

export const flagByCode = new Map(flags.map((f) => [f.code, f]));
